### ISSUE TITLE
build fails due to google-services.json missing

### ISSUE THREAD

**Issue by hades** [GnuCash-Pocket/gnucash-android#54]
## Steps to reproduce the behaviour
1. Download the repository (at commit ceb39e30181beb240de8ba9c44bb3a730e04dce2).
2. Open the project in Android Studio.
3. In menu select Build -> Make Project.

## Expected behaviour

The app builds.

## Actual behaviour

Build fails with:

```
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/hades/dev/gnucash-android/app/src/beta/debug/google-services.json
  /home/hades/dev/gnucash-android/app/src/debug/beta/google-services.json
  /home/hades/dev/gnucash-android/app/src/beta/google-services.json
  /home/hades/dev/gnucash-android/app/src/debug/google-services.json
  /home/hades/dev/gnucash-android/app/src/betaDebug/google-services.json
  /home/hades/dev/gnucash-android/app/google-services.json
```

## Suggested Resolution

* Add a dummy google-services.json that doesn't contain any secrets related to the actual production app.
* Update README to indicate how to generate a valid google-services.json.

**Comment by biaji** [comment]
Should go to https://console.firebase.google.com/ create a new project. And grab the json into project's app directory

**Comment by djbrown** [comment]
I suggest to document how to create the file but not to commit a dummy file.

The problem I see with the dummy file is that developmers might acceidentally commit their secrets more easily.
currently since the file is not in the git index by default (after cloning), if it is created and modified locally it wont automatically be available for staging. but once the (dummy) file is introduced to the git index, the gitignore won't blacklist the file anymore and changes (e.g. secret data) would more easily get overlooked.

**Comment by hades** [comment]
Thank you very much!
